name: Hyperion PPA
on: push

jobs:
  build-deb:
    name: ${{ matrix.distroName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-focal]
        include:
          - distro: ubuntu-focal
            distroName: Ubuntu Focal
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/gh-action-auto-dch@master
        name: Generate changelog
        with:
          fullname: Paulchen-Panther
          email: Paulchen-Panter@protonmail.com
          distro: ${{ matrix.distro }}

      - uses: legoktm/gh-action-build-deb@ubuntu-focal
        if: matrix.distro == 'ubuntu-focal'
        name: Build source package
        id: build-ubuntu-focal
        with:
          args: --no-sign

      - uses: legoktm/gh-action-dput@master
        name: Push to Launchpad
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:hyperion-project/hyperion.ng-snapshots
          packages: output/*_source.changes
