name: Hyperion PPA Build
on: push

env:
  DEBFULLNAME: "Hyperion Project"
  DEBEMAIL: "admin@hyperion-project.org"

jobs:
  build:
    name: Ubuntu ${{ matrix.distribution }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [Bionic, Focal, Groovy, Hirsute, Impish]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Import GPG signing key
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.LAUNCHPAD_GPG }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install devscripts debhelper-compat dput cmake build-essential qtbase5-dev libqt5serialport5-dev libqt5sql5-sqlite libqt5svg5-dev libqt5x11extras5-dev libusb-1.0-0-dev python3-dev libcec-dev libxcb-image0-dev libxcb-util0-dev libxcb-shm0-dev libxcb-render0-dev libxcb-randr0-dev libxrandr-dev libxrender-dev libavahi-core-dev libavahi-compat-libdnssd-dev libjpeg-dev libturbojpeg0-dev libssl-dev zlib1g-dev libflatbuffers-dev libprotobuf-dev protobuf-compiler libmbedtls-dev

      - name: Insert version and distribution into changelog/control file
        shell: bash
        run: |
          tr -d '\n' < version > temp && mv temp version
          echo "version=$(cat version)" >> $GITHUB_ENV
          echo "$(cat debian/control)" | sed "s/VERSION/"$(cat version)"/g" > debian/control
          dch --create --distribution $(echo ${{ matrix.distribution }} | tr '[:upper:]' '[:lower:]') --package "hyperion.ng" -v "$(cat version)-2~$(echo ${{ matrix.distribution }} | tr '[:upper:]' '[:lower:]')" "${{ github.event.commits[0].message }}"

      - name: Make package
        run: |
          tar cfv ../hyperion.ng_${{env.version}}.orig.tar .
          xz -9 ../hyperion.ng_${{env.version}}.orig.tar

      - name: Build package
        run: debuild -S -sa

      - name: Push to Launchpad
        run: dput ppa:hyperion-project/hyperion.ng-snapshots ../*_source.changes
