name: Hyperion PPA
on: push

jobs:
  build-deb:
    name: ${{ matrix.dockerName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-focal]
        include:
          - distro: ubuntu-focal
            dockerName: Ubuntu Focal (amd64)
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/gh-action-auto-dch@master
        with:
          fullname: Hyperion Project
          email: admin@hyperion-project.org
          distro: ${{ matrix.distro }}

      - uses: legoktm/gh-action-build-deb@ubuntu-focal
        if: matrix.distro == 'ubuntu-focal'
        name: Build package
        id: build-ubuntu-focal
        with:
          args: --no-sign

      - uses: legoktm/gh-action-dput@master
        name: Upload package
        with:
          gpg_key: ${{ secrets.LAUNCHPAD_GPG }}
          repository: ppa:hyperion-project/hyperion.ng-snapshots
          packages: output/*_source.changes
