name: Hyperion PPA
on: push

jobs:
  build-deb:
    name: ${{ matrix.dockerName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-focal]
        include:
          - distro: ubuntu-focal
            dockerName: Ubuntu Focal
    steps:
      - uses: actions/checkout@v2
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.LAUNCHPAD_GPG }}

      - name: Generate changelog
        uses: legoktm/gh-action-auto-dch@master
        with:
          fullname: Hyperion Project
          email: admin@hyperion-project.org
          distro: ${{ matrix.distro }}

      - name: Install devscripts, debhelper-compat, and dput
        run: sudo apt install devscripts debhelper-compat dput
        
      - name: Make package
        run: |
          tar cfv ../hyperion.ng_2.0.0-alpha.9.orig.tar .
          xz -9 ../hyperion.ng_2.0.0-alpha.9.orig.tar

      - name: Build source package
        run: debuild -S -sa
        
      - name: Push to Launchpad
        run: dput ppa:hyperion-project/hyperion.ng-snapshots ../*_source.changes
