name: Hyperion PPA
on: push

jobs:
  build-deb:
    name: ${{ matrix.dockerName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ubuntu-focal]
        include:
          - distro: ubuntu-focal
            dockerName: Ubuntu Focal
    steps:
      - uses: actions/checkout@v2
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v3.1.0
        with:
          gpg-private-key: ${{ secrets.LAUNCHPAD_GPG }}

      - name: Generate changelog
        uses: legoktm/gh-action-auto-dch@master
        with:
          fullname: Hyperion Project
          email: admin@hyperion-project.org
          distro: ${{ matrix.distro }}

      - name: Install dependencies
        run: |
          sudo apt install devscripts debhelper-compat dput git cmake build-essential qtbase5-dev libqt5serialport5-dev libqt5sql5-sqlite libqt5svg5-dev libqt5x11extras5-dev libusb-1.0-0-dev python3-dev libcec-dev libxcb-image0-dev libxcb-util0-dev libxcb-shm0-dev libxcb-render0-dev libxcb-randr0-dev libxrandr-dev libxrender-dev libavahi-core-dev libavahi-compat-libdnssd-dev libjpeg-dev libturbojpeg0-dev libssl-dev zlib1g-dev
        
      - name: Make package
        run: |
          tar cfv ../hyperion.ng_2.0.0-alpha.9.orig.tar .
          xz -9 ../hyperion.ng_2.0.0-alpha.9.orig.tar

      - name: Build source package
        run: debuild -S -sa
        
      - name: Push to Launchpad
        run: dput ppa:hyperion-project/hyperion.ng-snapshots ../*_source.changes
